ignition:
  version: "2.2.0"
  config:
    append:
      - source: "http://169.254.169.254/hetzner/v1/userdata"
storage:
  files:
    - filesystem: root
      path: /etc/hostname
      mode: 0644
      contents:
        remote:
          url: "http://169.254.169.254/hetzner/v1/metadata/hostname"